
--- CCTG

BEGIN;
UPDATE ONLY attribute SET name = 'discontinuereason' WHERE current_database() LIKE '%cctg%' AND attribute.name = 'discontinuationreason';
UPDATE ONLY attribute SET name = 'riskbehaviorcounsel' WHERE current_database() LIKE '%cctg%' AND attribute.name = 'riskbehaviorcounseling';
UPDATE ONLY attribute SET name = 'riskbehaviorprevgoal' WHERE current_database() LIKE '%cctg%' AND attribute.name = 'riskbehaviorpreviousgoal';
COMMIT;


--- MHEALTH

BEGIN;
UPDATE ONLY attribute SET name = 'creatinine_ccg' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'ChemistriesCreatinine' AND attribute.name = 'creatinine_cockcroftgalt';
UPDATE ONLY attribute SET name = 'sample0_actualtime' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample1' AND attribute.name = 'zero_sample_actualtime';
UPDATE ONLY attribute SET name = 'sample0_rifconc' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample1' AND attribute.name = 'zero_sample_rifampinconc';
UPDATE ONLY attribute SET name = 'sample0_schedtime' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample1' AND attribute.name = 'zero_sample_schedtime';
UPDATE ONLY attribute SET name = 'sample1_actualtime' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample2' AND attribute.name = 'one_sample_actualtime';
UPDATE ONLY attribute SET name = 'sample1_rifconc' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample2' AND attribute.name = 'one_sample_rifampinconc';
UPDATE ONLY attribute SET name = 'sample2_actualtime' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample3' AND attribute.name = 'two_sample_actualtime';
UPDATE ONLY attribute SET name = 'sample2_rifconc' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample3' AND attribute.name = 'two_sample_rifampinconc';
UPDATE ONLY attribute SET name = 'sample3_actualtime' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample4' AND attribute.name = 'three_sample_actualtime';
UPDATE ONLY attribute SET name = 'sample3_rifconc' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample4' AND attribute.name = 'three_sample_rifampinconc';
UPDATE ONLY attribute SET name = 'sample3_schedtime' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample4' AND attribute.name = 'three_sample_schedtime';
UPDATE ONLY attribute SET name = 'sample4_actualtime' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample5' AND attribute.name = 'four_sample_actualtime';
UPDATE ONLY attribute SET name = 'sample4_rifconc' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample5' AND attribute.name = 'four_sample_rifampinconc';
UPDATE ONLY attribute SET name = 'sample4_schedtime' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample5' AND attribute.name = 'four_sample_schedtime';
UPDATE ONLY attribute SET name = 'sample6_actualtime' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample6' AND attribute.name = 'six_sample_actualtime';
UPDATE ONLY attribute SET name = 'sample6_rifconc' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample6' AND attribute.name = 'six_sample_rifampinconc';
UPDATE ONLY attribute SET name = 'sample8_actualtime' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample7' AND attribute.name = 'eight_sample_actualtime';
UPDATE ONLY attribute SET name = 'sample8_rifconc' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample7' AND attribute.name = 'eight_sample_rifampinconc';
UPDATE ONLY attribute SET name = 'sample8_schedtime' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample7' AND attribute.name = 'eight_sample_schedtime';
UPDATE ONLY attribute SET name = 'sample24_actualtime' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample8' AND attribute.name = 'twentyfour_sample_actualtime';
UPDATE ONLY attribute SET name = 'sample24_inhconc' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample8' AND attribute.name = 'twentyfour_sample_inhconc';
UPDATE ONLY attribute SET name = 'sample24_rifconc' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample8' AND attribute.name = 'twentyfour_sample_rifampinconc';
UPDATE ONLY attribute SET name = 'sample24_schedtime' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample8' AND attribute.name = 'twentyfour_sample_schedtime';
UPDATE ONLY attribute SET name = 'sample24_sent' FROM schema  WHERE current_database() LIKE '%mhealth%' AND schema.id = attribute.schema_id AND schema.name = 'PkSubStudySample8' AND attribute.name = 'twentyfour_sample_sent';
COMMIT;

--- PIRC

BEGIN;
UPDATE ONLY attribute SET name = 'perm2contact' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'AEHPermissionToContactForFutureStudyOpportunities' AND attribute.name = 'study_opp_contact_later_date';
UPDATE ONLY attribute SET name = 'male_mo3' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'BaselineHistory' AND attribute.name = 'male_months3';
UPDATE ONLY attribute SET name = 'male_mo3_txt' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'BaselineHistory' AND attribute.name = 'male_months3_reason';
UPDATE ONLY attribute SET name = 'male_mo1' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'BaselineHistory' AND attribute.name = 'male_month1';
UPDATE ONLY attribute SET name = 'male_mo1_txt' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'BaselineHistory' AND attribute.name = 'male_month1_reason';
UPDATE ONLY attribute SET name = 'fem_mo3' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'BaselineHistory' AND attribute.name = 'female_months3';
UPDATE ONLY attribute SET name = 'fem_mo3_txt' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'BaselineHistory' AND attribute.name = 'female_months3_reason';
UPDATE ONLY attribute SET name = 'fem_mo1' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'BaselineHistory' AND attribute.name = 'female_month1';
UPDATE ONLY attribute SET name = 'fem_mo1_txt' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'BaselineHistory' AND attribute.name = 'female_month1_reason';
UPDATE ONLY attribute SET name = 'tran_mo3' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'BaselineHistory' AND attribute.name = 'transgender_months3';
UPDATE ONLY attribute SET name = 'tran_mo3_txt' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'BaselineHistory' AND attribute.name = 'transgender_months3_reason';
UPDATE ONLY attribute SET name = 'tran_mo1' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'BaselineHistory' AND attribute.name = 'transgender_month1';
UPDATE ONLY attribute SET name = 'tran_mo1_txt' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'BaselineHistory' AND attribute.name = 'transgender_month1_reason';
UPDATE ONLY attribute SET name = 'oral_rcpt' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'BaselineHistory' AND attribute.name = 'oral_receptive';
UPDATE ONLY attribute SET name = 'oral_nsrt' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'BaselineHistory' AND attribute.name = 'oral_insertive';
UPDATE ONLY attribute SET name = 'anal_rcpt' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'BaselineHistory' AND attribute.name = 'anal_receptive';
UPDATE ONLY attribute SET name = 'anal_nsrt' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'BaselineHistory' AND attribute.name = 'anal_insertive';
UPDATE ONLY attribute SET name = 'vag' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'BaselineHistory' AND attribute.name = 'vaginal';
UPDATE ONLY attribute SET name = 'hsv_first' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'BaselineHistory' AND attribute.name = 'genital_hsv_first';
UPDATE ONLY attribute SET name = 'hsv_recurring' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'BaselineHistory' AND attribute.name = 'genital_hsv_recurring';
UPDATE ONLY attribute SET name = 'drug_3mo' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'BaselineHistory' AND attribute.name = 'drug_3month';
UPDATE ONLY attribute SET name = 'drug_1mo' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'BaselineHistory' AND attribute.name = 'drug_1month';
UPDATE ONLY attribute SET name = 'test_kit' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'DetunedEIA' AND attribute.name = 'test_kit_type';
UPDATE ONLY attribute SET name = 'male_mo1' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'male_month1';
UPDATE ONLY attribute SET name = 'male_mo1chk' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'male_month1_reason';
UPDATE ONLY attribute SET name = 'male_new' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'male_new_count';
UPDATE ONLY attribute SET name = 'male_newchk' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'male_new_count_reason';
UPDATE ONLY attribute SET name = 'fem_mo1' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'female_month1';
UPDATE ONLY attribute SET name = 'fem_mo1chk' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'female_month1_reason';
UPDATE ONLY attribute SET name = 'fem_new' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'female_new_count';
UPDATE ONLY attribute SET name = 'fem_newchk' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'female_new_count_reason';
UPDATE ONLY attribute SET name = 'tran_mo1' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'transgender_month1';
UPDATE ONLY attribute SET name = 'tran_mo1chk' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'transgender_month1_reason';
UPDATE ONLY attribute SET name = 'tran_new' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'transgender_new_count';
UPDATE ONLY attribute SET name = 'tran_newchk' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'transgender_new_count_reason';
UPDATE ONLY attribute SET name = 'shared_needle_num' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'needle_sharing_month1';
UPDATE ONLY attribute SET name = 'shared_needle_numchk' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'needle_sharing_month1_reason';
UPDATE ONLY attribute SET name = 'injct_partner' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'needle_sharing_new_count';
UPDATE ONLY attribute SET name = 'injct_partnerchk' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'needle_sharing_new_count_reason';
UPDATE ONLY attribute SET name = 'oral_rcpt_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'oral_receptive';
UPDATE ONLY attribute SET name = 'oral_nsrt_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'oral_insertive';
UPDATE ONLY attribute SET name = 'anal_rcpt_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'anal_receptive';
UPDATE ONLY attribute SET name = 'anal_nsrt_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'anal_insertive';
UPDATE ONLY attribute SET name = 'vag_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'vaginal';
UPDATE ONLY attribute SET name = 'sexpart_type' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'sexual_behavior';
UPDATE ONLY attribute SET name = 'hsv_first' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'genital_hsv_first';
UPDATE ONLY attribute SET name = 'hsv_recurring' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'genital_hsv_recurring';
UPDATE ONLY attribute SET name = 'drug_1mo' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'FollowupHistory' AND attribute.name = 'drug_1month';
UPDATE ONLY attribute SET name = 'test_kit' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'GenitalSecretions' AND attribute.name = 'test_kit_type';
UPDATE ONLY attribute SET name = 'hcv_counsel' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVFollowUpDataForm' AND attribute.name = 'hcv_post_test_counseling';
UPDATE ONLY attribute SET name = 'counsel_date' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVFollowUpDataForm' AND attribute.name = 'hcv_post_test_counseling_date';
UPDATE ONLY attribute SET name = 'counsel_type' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVFollowUpDataForm' AND attribute.name = 'hcv_post_test_counseling_type';
UPDATE ONLY attribute SET name = 'no_counsel_why' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVFollowUpDataForm' AND attribute.name = 'hcv_post_test_counseling_none';
UPDATE ONLY attribute SET name = 'no_counsel_whytxt' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVFollowUpDataForm' AND attribute.name = 'hcv_post_test_counseling_none_other';
UPDATE ONLY attribute SET name = 'link2care' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVFollowUpDataForm' AND attribute.name = 'referred_med_care';
UPDATE ONLY attribute SET name = 'link2care_date' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVFollowUpDataForm' AND attribute.name = 'referred_med_care_date';
UPDATE ONLY attribute SET name = 'link2care_how' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVFollowUpDataForm' AND attribute.name = 'linkage_to_care_type';
UPDATE ONLY attribute SET name = 'link2care_howtxt' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVFollowUpDataForm' AND attribute.name = 'linkage_to_care_type_other';
UPDATE ONLY attribute SET name = 'no_link2care_why' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVFollowUpDataForm' AND attribute.name = 'linkage_to_care_reason_no';
UPDATE ONLY attribute SET name = 'no_link2care_whytxt' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVFollowUpDataForm' AND attribute.name = 'linkage_to_care_reason_no_other';
UPDATE ONLY attribute SET name = 'hcv_appt' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVFollowUpDataForm' AND attribute.name = 'documentation_first_med_visit';
UPDATE ONLY attribute SET name = 'hcv_appt_date' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVFollowUpDataForm' AND attribute.name = 'documentation_first_med_visit_date';
UPDATE ONLY attribute SET name = 'no_appt_why' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVFollowUpDataForm' AND attribute.name = 'documentation_first_med_visit_none';
UPDATE ONLY attribute SET name = 'no_appt_whytxt' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVFollowUpDataForm' AND attribute.name = 'documentation_first_med_visit_none_other';
UPDATE ONLY attribute SET name = 'hcv_meds' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVFollowUpDataForm' AND attribute.name = 'hcv_art';
UPDATE ONLY attribute SET name = 'hcv_meds_date' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVFollowUpDataForm' AND attribute.name = 'hcv_art_start_date';
UPDATE ONLY attribute SET name = 'hcv_meds_type' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVFollowUpDataForm' AND attribute.name = 'hcv_art_type';
UPDATE ONLY attribute SET name = 'reported' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVFollowUpDataForm' AND attribute.name = 'reported_to_surveillance';
UPDATE ONLY attribute SET name = 'reported_date' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVFollowUpDataForm' AND attribute.name = 'reported_to_surveillance_date';
UPDATE ONLY attribute SET name = 'hiv_pos_status' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVSupplementalCDCForm' AND attribute.name = 'hiv_positive_status';
UPDATE ONLY attribute SET name = 'hiv_pos_source' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVSupplementalCDCForm' AND attribute.name = 'hiv_positive_status_source';
UPDATE ONLY attribute SET name = 'hep_vaccine_ever' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVSupplementalCDCForm' AND attribute.name = 'hepatitis_vaccine_ever';
UPDATE ONLY attribute SET name = 'hep_vaccine_type' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HCVSupplementalCDCForm' AND attribute.name = 'hepatitis_vaccine_type';
UPDATE ONLY attribute SET name = 'test_kit' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HIVSerologySelfReport' AND attribute.name = 'test_kit_type';
UPDATE ONLY attribute SET name = 'hepb_surf_antigen' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'Hepatitis' AND attribute.name = 'hep_b_surface_antigen';
UPDATE ONLY attribute SET name = 'hepb_surf_antibody' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'Hepatitis' AND attribute.name = 'hep_b_surface_antibody';
UPDATE ONLY attribute SET name = 'hepb_core_antibody' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'Hepatitis' AND attribute.name = 'hep_b_core_antibody';
UPDATE ONLY attribute SET name = 'test_kit' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HivNAT' AND attribute.name = 'test_kit_type';
UPDATE ONLY attribute SET name = 'test_kit' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'HivSerology' AND attribute.name = 'test_kit_type';
UPDATE ONLY attribute SET name = 'previous_et' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'had_early_test';
UPDATE ONLY attribute SET name = 'sexpart_et_name' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'someone_had_early_test';
UPDATE ONLY attribute SET name = 'sexpart_et' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'sex_with_someone_had_early_test';
UPDATE ONLY attribute SET name = 'date_last_neg' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'date_last_negative';
UPDATE ONLY attribute SET name = 'male_vag_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'male_vaginal_condom_use';
UPDATE ONLY attribute SET name = 'male_anal_nsrt_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'male_anal_insertive_condom_use';
UPDATE ONLY attribute SET name = 'male_anal_rcpt_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'male_anal_receptive_condom_use';
UPDATE ONLY attribute SET name = 'fem_number' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'female_number';
UPDATE ONLY attribute SET name = 'fem_oral_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'female_oral_sex';
UPDATE ONLY attribute SET name = 'fem_vag_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'female_vaginal_condom_use';
UPDATE ONLY attribute SET name = 'fem_anal_nsrt_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'female_anal_insertive_condom_use';
UPDATE ONLY attribute SET name = 'tran_number' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'transgender_number';
UPDATE ONLY attribute SET name = 'tran_oral_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'transgender_oral_sex';
UPDATE ONLY attribute SET name = 'tran_vag_nsrt_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'transgender_vaginal_insertive_condom_use';
UPDATE ONLY attribute SET name = 'male_vag_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'male_vaginal_sex';
UPDATE ONLY attribute SET name = 'tran_vag_rcpt_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'transgender_vaginal_receptive_condom_use';
UPDATE ONLY attribute SET name = 'tran_anal_nsrt_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'transgender_anal_insertive_condom_use';
UPDATE ONLY attribute SET name = 'male_anal_nsrt_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'male_anal_insertive_sex';
UPDATE ONLY attribute SET name = 'tran_anal_rcpt_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'transgender_anal_receptive_condom_use';
UPDATE ONLY attribute SET name = 'male_rcpt_anal_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'male_receptive_anal_sex';
UPDATE ONLY attribute SET name = 'fem_vag_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'female_vaginal_sex';
UPDATE ONLY attribute SET name = 'msm_vag_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'msm_vaginal_condom_use';
UPDATE ONLY attribute SET name = 'msm_anal_rcpt_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'msm_anal_receptive_condom_use';
UPDATE ONLY attribute SET name = 'fem_nsrt_anal_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'female_insertve_anal_sex';
UPDATE ONLY attribute SET name = 'xwrkr_type' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'sex_worker_type';
UPDATE ONLY attribute SET name = 'xwrkr_oral_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'sex_worker_oral_sex';
UPDATE ONLY attribute SET name = 'xwrkr_vag_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'sex_worker_vaginal_condom_use';
UPDATE ONLY attribute SET name = 'tran_nsrt_vag_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'transgender_insertive_vaginal_sex';
UPDATE ONLY attribute SET name = 'xwrkr_anal_nsrt_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'sex_worker_anal_insertive_condom_use';
UPDATE ONLY attribute SET name = 'xwrkr_anal_rcpt_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'sex_worker_anal_receptive_condom_use';
UPDATE ONLY attribute SET name = 'tran_rcpt_vag_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'transgender_receptive_vaginal_sex';
UPDATE ONLY attribute SET name = 'xwrkr_12mo' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'sex_worker_12months';
UPDATE ONLY attribute SET name = 'tran_nsrt_anal_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'transgender_insertive_anal_sex';
UPDATE ONLY attribute SET name = 'tran_rcpt_anal_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'transgender_receptive_anal_sex';
UPDATE ONLY attribute SET name = 'injct_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'injection_sex';
UPDATE ONLY attribute SET name = 'injct_oral_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'injection_oral_sex';
UPDATE ONLY attribute SET name = 'injct_vag_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'injection_vaginal_condom_use';
UPDATE ONLY attribute SET name = 'msm_vag_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'msm_vaginal_sex';
UPDATE ONLY attribute SET name = 'injct_anal_nsrt_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'injection_anal_insertive_condom_use';
UPDATE ONLY attribute SET name = 'injct_anal_rcpt_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'injection_anal_receptive_condom_use';
UPDATE ONLY attribute SET name = 'msm_anal_rcpt_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'msm_anal_receptive_sex';
UPDATE ONLY attribute SET name = 'hiv_vag_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'hiv_vaginal_condom_use';
UPDATE ONLY attribute SET name = 'xwrkr_vag_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'sex_worker_vaginal_sex';
UPDATE ONLY attribute SET name = 'hiv_anal_nsrt_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'hiv_anal_insertive_condom_use';
UPDATE ONLY attribute SET name = 'hiv_anal_rcpt_cndm' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'hiv_anal_receptive_condom_use';
UPDATE ONLY attribute SET name = 'xwrkr_nsrt_anal_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'sex_worker_insertive_anal_sex';
UPDATE ONLY attribute SET name = 'xwrkr_rcpt_anal_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'sex_worker_receptive_anal_sex';
UPDATE ONLY attribute SET name = 'drug_12mo' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'drug_12months';
UPDATE ONLY attribute SET name = 'injct_vag_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'injection_vaginal_sex';
UPDATE ONLY attribute SET name = 'injct_anal_nsrt_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'injection_anal_insertive_sex';
UPDATE ONLY attribute SET name = 'injct_anal_rcpt_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'injection_anal_receptive_sex';
UPDATE ONLY attribute SET name = 'std_ever' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'lifetime';
UPDATE ONLY attribute SET name = 'hiv_vag_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'hiv_vaginal_sex';
UPDATE ONLY attribute SET name = 'hepa_b_vaccine' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'vaccination';
UPDATE ONLY attribute SET name = 'hiv_anal_nsrt_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'hiv_anal_insertive_sex';
UPDATE ONLY attribute SET name = 'hiv_anal_rcpt_sex' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'hiv_anal_receptive_sex';
UPDATE ONLY attribute SET name = 'drug_ever' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IEarlyTest' AND attribute.name = 'drug_lifetime_use';
UPDATE ONLY attribute SET name = 'test_kit' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'IFA' AND attribute.name = 'test_kit_type';
UPDATE ONLY attribute SET name = 'test_kit' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'LumbarPuncture' AND attribute.name = 'test_kit_type';
UPDATE ONLY attribute SET name = 'test_kit' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'RapidTest' AND attribute.name = 'test_kit_type';
UPDATE ONLY attribute SET name = 'rapid2_test_kit' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'RapidTest' AND attribute.name = 'verify_test_kit_type';
UPDATE ONLY attribute SET name = 'rapid2' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'RapidTest' AND attribute.name = 'verify_result';
UPDATE ONLY attribute SET name = 'hsv2_anal_pcr_comp' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'STD' AND attribute.name = 'hsv2_anal_pcr_test_done';
UPDATE ONLY attribute SET name = 'crnt_hsv2' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'STD' AND attribute.name = 'current_hsv2';
UPDATE ONLY attribute SET name = 'date_crnt_hsv2_began' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'STD' AND attribute.name = 'date_current_hsv2_began';
UPDATE ONLY attribute SET name = 'prev_hsv2' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'STD' AND attribute.name = 'previous_hsv2';
UPDATE ONLY attribute SET name = 'date_prev_hsv2_began' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'STD' AND attribute.name = 'date_previous_hsv2_began';
UPDATE ONLY attribute SET name = 'date_prev_hsv2_ended' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'STD' AND attribute.name = 'date_previous_hsv2_ended';
UPDATE ONLY attribute SET name = 'prev_hsv2_1mo' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'STD' AND attribute.name = 'previous_hsv2_1mo';
UPDATE ONLY attribute SET name = 'test_kit' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'ViralLoad' AND attribute.name = 'test_kit_type';
UPDATE ONLY attribute SET name = 'test_kit' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'WesternBlot' AND attribute.name = 'test_kit_type';
UPDATE ONLY attribute SET name = 'test_kit' FROM schema WHERE current_database() LIKE '%avrc%' AND schema.name = 'WesternBlotSelfReport' AND attribute.name = 'test_kit_type';

UPDATE ONLY attribute SET name = 'rec_drug_use' FROM schema WHERE current_database() LIKE '%avrc%' AND attribute.type = 'object' AND attribute.name = 'recreational_drug_use';
UPDATE ONLY attribute SET name = 'needle_sharing' FROM schema WHERE current_database() LIKE '%avrc%' AND attribute.type = 'object' AND attribute.name = 'neddle_sharing_partners';
UPDATE ONLY attribute SET name = 'likert_risk' FROM schema WHERE current_database() LIKE '%avrc%' AND attribute.type = 'object' AND attribute.name = 'likert_risk_questions';

UPDATE schema SET name = 'AehPerm2Contact' WHERE current_database() LIKE '%avrc%' AND name = 'AEHPermissionToContactForFutureStudyOpportunities';

COMMIT;

-- Lock the variable length

ALTER TABLE attribute ALTER name TYPE VARCHAR(20);
